// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using study_buddys_backend_v2.Context;

#nullable disable

namespace study_buddys_backend_v2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250422163119_AddDirectMessagesTable")]
    partial class AddDirectMessagesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("study_buddys_backend_v2.Models.CommunityChatModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommunityModelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserIdSender")
                        .HasColumnType("int");

                    b.Property<string>("UserSenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommunityModelId");

                    b.ToTable("CommunityChatModel");
                });

            modelBuilder.Entity("study_buddys_backend_v2.Models.CommunityMemberModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommunityModelId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommunityModelId");

                    b.ToTable("CommunityMemberModel");
                });

            modelBuilder.Entity("study_buddys_backend_v2.Models.CommunityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommunityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunityDifficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CommunityIsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("CommunityIsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("CommunityMemberCount")
                        .HasColumnType("int");

                    b.Property<string>("CommunityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommunityOwnerID")
                        .HasColumnType("int");

                    b.Property<string>("CommunityOwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunityRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunitySubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCommunityOwner")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Communitys");
                });

            modelBuilder.Entity("study_buddys_backend_v2.Models.DirectMessageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DirectMessages");
                });

            modelBuilder.Entity("study_buddys_backend_v2.Models.UserModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommunityRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JoinedCommunitys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnedCommunitys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("study_buddys_backend_v2.Models.CommunityChatModel", b =>
                {
                    b.HasOne("study_buddys_backend_v2.Models.CommunityModel", null)
                        .WithMany("CommunityChats")
                        .HasForeignKey("CommunityModelId");
                });

            modelBuilder.Entity("study_buddys_backend_v2.Models.CommunityMemberModel", b =>
                {
                    b.HasOne("study_buddys_backend_v2.Models.CommunityModel", null)
                        .WithMany("CommunityMembers")
                        .HasForeignKey("CommunityModelId");
                });

            modelBuilder.Entity("study_buddys_backend_v2.Models.CommunityModel", b =>
                {
                    b.Navigation("CommunityChats");

                    b.Navigation("CommunityMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
